### PR TITLE
Disallow arrow functions and enforce space consistency.

### PR DESCRIPTION
**Pull request by satazor**

### CODE REVIEW

**Comment by zebateira** [comment]
image

**Comment by zebateira** [comment]
ok fine 😭

**Review by zebateira — APPROVED** [review]

**Review by antoniocapelo — APPROVED** [review]

**Review by vasco-santos — APPROVED** [review]
Agree with disallowing the arrow functions.

**Comment by ruipneves** [comment]
Farewell my react's best friends 😂

**Review by ruipneves — APPROVED** [review]

**Comment by satazor** [comment]
The majority approved, this is a democracy.

**Pull request merged**
